"""add notification table

Revision ID: 8b0b5b9281f9
Revises: 
Create Date: 2026-04-05 19:54:29.338894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b0b5b9281f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               nullable=False)
    op.drop_index(op.f('idx_user_id'), table_name='users')
    op.drop_index(op.f('user_id'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('idx_user_id'), 'users', ['user_id'], unique=False)
    op.alter_column('users', 'user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               nullable=True)
    # ### end Alembic commands ###
